#!/bin/bash

# Install homebrew
ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go/install)"

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade

# Install more recent versions of some OS X tools
brew tap homebrew/dupes

# System utilities
brew install ack
brew install ssh-copy-id
brew install git hub
brew install mercurial
brew install wget --enable-iri
brew install ngrep
brew install tree
brew install colordiff

# Programming tools
brew install appledoc doxygen
brew install rbenv ruby-build
brew install node
brew install cmake

# Multimedia
brew install imagemagick --use-jpeg2000 --use-tiff
brew install graphviz --with-bindings --with-app
brew install lame
brew install ffmpeg --with-libvpx --with-theora

# Other stuff
brew install youtube-dl
brew install webkit2png
brew install lynx

# Remove outdated versions from the cellar
brew cleanup
