#!/bin/bash

# Install homebrew
ruby <(curl -fsSkL raw.github.com/mxcl/homebrew/go)

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade

# Install more recent versions of some OS X tools
brew tap homebrew/dupes

# System utilities
brew install ack
brew install ssh-copy-id
brew install git hub
brew install wget --enable-iri
brew install ngrep
brew install tree
brew install colordiff

# Other software
brew install imagemagick --use-jpeg2000 --use-tiff
brew install graphviz --with-bindings --with-app
brew install lame
brew install ffmpeg --with-libvpx --with-theora
brew install postgres
brew install mongodb
brew install node
brew install android-sdk
brew install youtube-dl
brew install webkit2png
brew install lynx

# Remove outdated versions from the cellar
brew cleanup
