#!/bin/bash

# Install homebrew
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade

# System utilities
brew install ack dos2unix tree ssh-copy-id \
  wget tree rename nmap gnu-sed zsh pstree \
  telnet

# Programming tools
brew install ninja node cmake doxygen \
  rbenv ruby-build clang-format cloc \
  lua pidcat

# Multimedia
brew install imagemagick youtube-dl \
  graphviz lame webkit2png

brew tap varenc/ffmpeg
brew install varenc/ffmpeg/ffmpeg --with-fdk-aac --with-openssl --with-libmodplug --with-rtmpdump

# Remove outdated versions from the cellar
brew cleanup
